---
- name: Create Directory 
  file: path={{ base_path }}/zookeeper state=directory recurse=yes owner={{ user_name }}
  sudo: yes

- name: Download Zookeeper
  get_url: url={{ apache_server }}/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz dest={{ base_path }}/zookeeper

- name: Untar Zookeeper
  unarchive: src={{ base_path }}/zookeeper/zookeeper-{{ zookeeper_version }}.tar.gz dest={{ base_path }}/zookeeper copy=no

- name: Copy config Zookeeper
  copy: src=zoo.cfg dest={{ base_path }}/zookeeper/zookeeper-{{ zookeeper_version }}/conf/zoo.cfg
