---
- hosts: supervisor 
  roles:
    - configs

- hosts: nimbus
  roles:
    - configs
    - masterconfig

- hosts: zookeeper
  roles:
    - configs
    - zookeeper

- hosts: storm
  roles:
    - storm
