---
- hosts: zookeeper
  roles:
    - runzookeeper

- hosts: nimbus
  roles:
    - runnimbus
  post_tasks: 
    - pause: seconds=30
- hosts: supervisor
  roles:
    - runsupervisor

- hosts: nimbus
  roles:
    - runui
