---
- name: Create Directory 
  file: path={{ base_path }}/kafka state=directory recurse=yes owner={{ user_name }}

- name: Download Kafka
  get_url: url={{ apache_server }}/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{kafka_version}}.tgz dest={{ base_path }}/kafka

- name: Untar Kafka
  unarchive: src={{ base_path }}/kafka/kafka_{{ kafka_scala_version }}-{{kafka_version}}.tgz dest={{ base_path }}/kafka copy=no

- name: Copy config Kafka
  copy: src=server.properties dest={{ base_path }}/kafka/kafka_{{ kafka_scala_version }}-{{kafka_version}}/config/server.properties

- name: "Modifying conf file"
  lineinfile:   dest={{ base_path }}/kafka/kafka_{{ kafka_scala_version }}-{{kafka_version}}/config/server.properties
                regexp='broker.id='
                line="broker.id={{ brokerid }}"
                state=present
  sudo: yes

