---
base_path: /mnt/scratch/bilal/ansible-test
user_name: ubuntu
storm_version: 1.0.1
kafka_version: 0.9.0.0
kafka_scala_version: "2.10"
zookeeper_version: 3.4.10
hadoop_version: 2.6.5
redis_version: 3.2.4
apache_server: http://www-eu.apache.org/dist
private_key_file: ~/Downloads/bilal_key_eu.pem
