---
base_path: /home/ubuntu/ansible-test
user_name: ubuntu
storm_version: 1.0.1
kafka_version: 0.9.0.0
kafka_scala_version: "2.10"
hadoop_version: 2.6.2
redis_version: 3.2.4
apache_server: http://www-us.apache.org/dist

