---
- name: Create Directory
  file: path={{ base_path  }}/storm state=directory recurse=yes owner={{ user_name }}
  sudo: yes

- name: Download Storm
  get_url: url=http://www-eu.apache.org/dist/storm/apache-storm-{{ storm_version }}/apache-storm-{{ storm_version }}.tar.gz dest={{ base_path  }}/storm/apache-storm-{{ storm_version }}.tar.gz

- name: Untar Storm
  unarchive: src={{ base_path }}/storm/apache-storm-{{ storm_version }}.tar.gz dest={{ base_path  }}/storm copy=no creates={{ base_path  }}/storm/apache-storm-{{ storm_version }}

- name: Copy config Storm
  copy: src=storm_conf.yaml dest={{ base_path  }}/storm/apache-storm-{{ storm_version }}/conf/storm.yaml

- name: Copy logback configuration
  copy: src=cluster.xml dest={{ base_path  }}/storm/apache-storm-{{ storm_version }}/logback/cluster.xml
